### ISSUE TITLE
can this program calculate the Groebner Basis in rational number field rather than finite field, such as Z_{32003}?.

### ISSUE THREAD

**Issue by zhangyusi-hub** [svrnm/parallelGBC#1]
Hello Severin, I do a research in the polynomial embedded system, I want to ask you can this program calculate the Groebner Basis in rational number field rather than finite field, such as Z_{32003}?.

**Comment by svrnm** [comment]
Hey @zhangyusi-hub, 

unfortunately no, this code is optimized for computations over finite fields, because with this restriction the most computation time is spend in matrix multiplication, which is optimized in this project. If you remove this restriction and compute over rational numbers, the complexity moves over to the computation of individual numbers in the matrix cells. 

As you can see from this project I am not involved with Gröbner basis computation for a long while, to get more recent insights, you might check various projects by researchers like @ederc, or checkout https://github.com/oscar-system and https://github.com/Singular

**Comment by zhangyusi-hub** [comment]
thanks for your recommendation.

**Comment by ederc** [comment]
@zhangyusi-hub You can give [msolve](https://github.com/algebraic-solving/msolve) a try. It includes GB computations and system solving over finite fields and QQ.

**Comment by svrnm** [comment]
thanks for following up @ederc :-)

**Comment by zhangyusi-hub** [comment]
@ederc thanks
